name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies (Visual Studio 2019)
    - name: Setup MSBuild environment
      uses: microsoft/setup-msbuild@v1

    # Step 3: Build the project using MSBuild
    - name: Build ViGEmClient.dll
      run: |
        msbuild.exe ViGEmClient.sln /p:Configuration=Release_DLL /p:Platform=x64

    # Step 4: Upload the built DLL as an artifact
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLL
        path: |
          bin/Release/x64/ViGEmClient.dll
